import Head from 'next/head'
import Image from 'next/image';
import Header from '../components/Header'
import Navbar from '../components/Nav';
import Results from '../components/Results';
import requests from "../utils/requests";


export default function Home({results}) {
  // console.log('>>>  home results', results);

  return (
    <div>
      <Head>
        <title>Hulu-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Results results={results}/>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  // console.log('>>>> genre', genre);
  const request = await fetch(
    `https://api.themoviedb.org/3/${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => {
    return res.json();
  });

  // console.log('>>> request', request);
  
  return  {
      props : {
          results : request.results,
      }
  }
}